# Generated by Django 3.2 on 2023-07-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default='59f1f2c1-1291-40e6-9bd3-b1cb8d2bdd4b'),
        ),
    ]
