# Generated by Django 3.2 on 2023-06-30 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='name',
            field=models.CharField(default='default name', max_length=256, verbose_name='Название жанра'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(default='default slug', unique=True, validators=[django.core.validators.RegexValidator(message='Слаг для страницы с жанром может содержать только латинскиебуквы и любые цифры, а также дефис и нижнее подчеркивание', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Адрес для страницы с жанром'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(default='default name', max_length=256, verbose_name='Название произведения'),
        ),
    ]
