# Generated by Django 3.2 on 2023-06-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
