# Generated by Django 3.2 on 2023-06-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_code',
            field=models.CharField(default='be264df1-387d-4a2a-b950-0bbab34b5047', max_length=50),
        ),
    ]
