# Generated by Django 3.2 on 2023-06-28 22:09

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_customuser_bio"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
    ]
