# Generated by Django 3.2 on 2023-07-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_alter_customuser_confirmation_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="confirmation_code",
            field=models.UUIDField(default="8e39ecae-c47f-4fa3-8041-ec4cfe719511"),
        ),
    ]
