# Generated by Django 3.2 on 2023-06-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0003_auto_20230629_0109"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("USER", "User"),
                    ("MODERATOR", "Moderator"),
                    ("ADMIN", "Administrator"),
                ],
                default="USER",
                max_length=50,
            ),
        ),
    ]
