# Generated by Django 3.2 on 2023-07-08 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Слаг для страницы с жанром может содержать только латинские буквы и любые цифры, а также дефис и нижнее подчеркивание', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Адрес для страницы с категорией'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default='3d1fdf13-f9c8-4e85-adfc-b730e0c56cd7'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('moderator', 'moderator'), ('admin', 'admin')], default='user', max_length=50),
        ),
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Слаг для страницы с жанром может содержать только латинские буквы и любые цифры, а также дефис и нижнее подчеркивание', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Адрес для страницы с жанром'),
        ),
    ]
