# Generated by Django 3.2 on 2023-07-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20230708_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default='781739af-7318-4a88-ab33-c4ca9b75e633'),
        ),
    ]
